services:
  eureka-server:
    image: softbank2025/server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices
    environment:
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.server.wait-time-in-ms-when-sync-empty=0

  gateway:
    image: softbank2025/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  frontend:
    image: softbank2025/fe
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  deploy:
    image: softbank2025/deploy
    container_name: deploy
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

  user:
    image: softbank2025/user
    container_name: user
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

networks:
  microservices:
    driver: bridge

volumes:
  eureka-data:
