services:
  server:
    image: kwa06001/server:latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    ports:
      - "8761:8761"
    networks:
      - microservices
    environment:
      - SERVER_PORT=8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.server.wait-time-in-ms-when-sync-empty=0
      - eureka.server.enable-self-preservation=false

  gateway:
    image: kwa06001/gateway:latest
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://server:8761/eureka/
    restart: unless-stopped

  fe:
    image: kwa06001/fe:latest
    build:
      context: .
      dockerfile: ./fe/Dockerfile
    container_name: fe
    ports:
      - "8081:8081"
    depends_on:
      - server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://server:8761/eureka/
    restart: unless-stopped

  deploy:
    image: kwa06001/deploy:latest
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    container_name: deploy
    ports:
      - "8082:8082"
    depends_on:
      - server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://server:8761/eureka/
    restart: unless-stopped

  user:
    image: kwa06001/user:latest
    build:
      context: .
      dockerfile: ./user/Dockerfile
    container_name: user
    ports:
      - "8083:8083"
    depends_on:
      - server
    networks:
      - microservices
    environment:
      - eureka.client.service-url.defaultZone=http://server:8761/eureka/
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - server
      - gateway
      - fe
      - deploy
      - user
    networks:
      - microservices

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    env_file:
      - ./.env
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
    depends_on:
      - prometheus
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  eureka-data:
