global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-msa'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8080']
        labels:
          application: 'gateway'
      - targets: ['fe:8081']
        labels:
          application: 'frontend'
      - targets: ['deploy:8082']
        labels:
          application: 'deploy'
      - targets: ['user:8083']
        labels:
          application: 'user'
      - targets: ['server:8761']
        labels:
          application: 'eureka'